# 00.data.tf

# data "gha_tf_azure" "base" {
#     AZURE_RESOURCE_GROUP_NAME = "${var.AZURE_RESOURCE_GROUP_NAME}"
#     AZURE_STORAGE_ACCOUNT_NAME = "${ar.AZURE_STORAGE_ACCOUNT_NAME}"
#     AZURE_STORAGE_ACCOUNT_CONTAINER_NAME = "${var.AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}"
#     AZURE_STORAGE_ACCOUNT_BLOB_NAME = "${var.AZURE_STORAGE_ACCOUNT_BLOB_NAME}"
#     AZURE_TENANT_ID = "${var.ARM_TENANT_ID}"
#     AZURE_CLIENT_ID = "${var.ARM_CLIENT_ID}"
#     AZURE_CLIENT_SECRET = "${var.ARM_CLIENT_SECRET}"
#     AZURE_SUBSCRIPTION_ID = "${var.ARM_SUBSCRIPTION_ID}"
# }

locals {

}





